### ISSUE TITLE
Complex max pooling

### ISSUE THREAD

**Issue by NEGU93** [ivannz/cplxmodule#17]
Is there an implementaion of a complex max pooling?

**Comment by ivannz** [comment]
Complex max pooling, i assume, would be a split activation, meaning that it would be applied to the real and imag components independently. In this case, you could do the following: ```python
import torch

from torch.nn import MaxPool2d

from cplxmodule import Cplx
from cplxmodule.nn import CplxToCplx

input = Cplx(real=torch.randn(1, 4, 8, 8), imag=torch.randn(1, 4, 8, 8))

# create a split-layer
CplxMaxPool2d = CplxToCplx[MaxPool2d]

layer = CplxMaxPool2d(2, 2)

layer(input)
```

**Comment by NEGU93** [comment]
Actually, that would destroy the phase information as the max of real and imaginary can be from different indices. I was thinking more the application listed in Cao et al. "Pixel-Wise PolSAR Image Classification via a Novel Complex-Valued Deep Fully Convolutional Network" or Zhang et al. "Complex-Valued Convolutional Neural Network and Its Application in Polarimetric SAR Image Classification".

In both cases they apply the max-pooling to the absolute value.

**Comment by ivannz** [comment]
I apologise for ignoring your issue for so long @NEGU93 . I have implemented the pooling layers you suggested, and hope they are still relevant to your work or research.
